apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: flavius-e2e-gitops
  description: This is GitOps manifest for flavius-e2e   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: flavius-e2e
    janus-idp.io/tekton: flavius-e2e 
    backstage.io/kubernetes-id: flavius-e2e 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:flavius-e2e
