apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: flavius-e2e
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flavius-e2e 
  name: flavius-e2e
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: flavius-e2e 
